### ISSUE TITLE
Testing fails without a copy of Galaxy downloaded

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#274]
Recently started getting this error:

```
'NoneType' object has no attribute 'endswith'
<snip>
File "/home/hxr/projects/python-galaxy-tools/env/local/lib/python2.7/site-packages/planemo/galaxy_config.py", line 237, in galaxy_config
    write_file(shed_tool_conf, shed_tool_conf_contents)
  File "/home/hxr/projects/python-galaxy-tools/env/local/lib/python2.7/site-packages/planemo/io.py", line 63, in write_file
    with open(path, "w") as f:
IOError: [Errno 2] No such file or directory: '/tmp/tmptFlNTG/galaxy-dev/config/shed_tool_conf.xml'
```

which seems to be a result of a missing copy of galaxy, judging by the output result:

```
$ ls /tmp/tmptFlNTG/
empty_tool_conf.xml  galaxy.ini  job_metrics_conf.xml  shed_tools  tool_conf.xml  tool_sheds_conf.xml
```

One of my undergraduates got this error and I assumed it was user error, but then I got it too on a fresh install. Passing the `--install_galaxy` flag every time seems to solve the issue, when/why did that become non-default? Minor UX issue.

**Comment by martenson** [comment]
Also if you have ```galaxy_root``` specified in .planemo.yml you won't encounter it; otherwise I confirm it.

**Comment by jmchilton** [comment]
Maybe introduced in https://github.com/galaxyproject/planemo/commit/e67e31bc02ff293bff92d4701171f4fa24126974

**Comment by erasche** [comment]
Thanks @jmchilton
