### ISSUE TITLE
docker_galaxy engine broken in latest release

### ISSUE THREAD

**Issue by simleo** [galaxyproject/planemo#1160]
Running Planemo with the `docker_galaxy` engine leads to:

```
AttributeError: 'DockerGalaxyConfig' object has no attribute 'log_file'
```

**This affects release 0.74.3, but not 0.74.2**.

The problem is still present in the [current master](https://github.com/galaxyproject/planemo/tree/7edabe7a4b36f1371f95569b1ec43933c0f3f7b4).

Steps to reproduce (Docker 20.10.5 on Ubuntu 18.0):

```
planemo test --engine docker_galaxy --docker_galaxy_image bgruening/galaxy-stable:20.09 --extra_tools tests/data/repos/single_tool/cat.xml tests/data/wf2.ga
```

Full error:

```
Traceback (most recent call last):
  File "/home/simleo/repos/planemo/venv/bin/planemo", line 11, in <module>
    load_entry_point('planemo==0.74.4', 'console_scripts', 'planemo')()
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/planemo-0.74.4-py3.6.egg/planemo/cli.py", line 98, in handle_blended_options
    return f(*args, **kwds)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/planemo-0.74.4-py3.6.egg/planemo/commands/cmd_test.py", line 82, in cli
    return_value = test_runnables(ctx, runnables, original_paths=uris, **kwds)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/planemo-0.74.4-py3.6.egg/planemo/engine/test.py", line 25, in test_runnables
    test_data = engine.test(runnables)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/planemo-0.74.4-py3.6.egg/planemo/engine/interface.py", line 80, in test
    test_results = self._collect_test_results(test_cases)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/planemo-0.74.4-py3.6.egg/planemo/engine/interface.py", line 99, in _collect_test_results
    run_response = self._run_test_case(test_case)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/planemo-0.74.4-py3.6.egg/planemo/engine/galaxy.py", line 50, in _run_test_case
    return super(GalaxyEngine, self)._run_test_case(test_case)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/planemo-0.74.4-py3.6.egg/planemo/engine/interface.py", line 126, in _run_test_case
    run_response = self._run(runnable, job_path)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/planemo-0.74.4-py3.6.egg/planemo/engine/galaxy.py", line 35, in _run
    with self.ensure_runnables_served([runnable]) as config:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/planemo-0.74.4-py3.6.egg/planemo/engine/galaxy.py", line 104, in ensure_runnables_served
    with serve_daemon(self._ctx, runnables, **self._serve_kwds()) as config:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/planemo-0.74.4-py3.6.egg/planemo/galaxy/serve.py", line 109, in serve_daemon
    config = serve(ctx, runnables, **kwds)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/planemo-0.74.4-py3.6.egg/planemo/galaxy/serve.py", line 25, in serve
    return _serve(ctx, runnables, **kwds)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/planemo-0.74.4-py3.6.egg/planemo/galaxy/serve.py", line 45, in _serve
    with galaxy_config(ctx, runnables, **kwds) as config:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/simleo/repos/planemo/venv/lib/python3.6/site-packages/planemo-0.74.4-py3.6.egg/planemo/galaxy/config.py", line 220, in galaxy_config
    log_thread = threading.Thread(target=read_log, args=(ctx, config.log_file))
AttributeError: 'DockerGalaxyConfig' object has no attribute 'log_file'
```

With Planemo 0.74.2, instead, the above command runs fine.

**Comment by nsoranzo** [comment]
Introduced in https://github.com/galaxyproject/planemo/pull/1142 , I believe.
